
DROP TABLE "T_NULL_LINK_DEMO_SRC";
DROP TABLE "T_NULL_LINK_DEMO_DEST";

CREATE TABLE "T_NULL_LINK_DEMO_SRC" (
    "ID" VARCHAR2(256 BYTE) NOT NULL,
	"VALUE" VARCHAR2(256 BYTE) NOT NULL,
	"DEST_BIZ_KEY" VARCHAR2(256 BYTE),
	CONSTRAINT "T_NULL_LINK_DEMO_SRC_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
) TABLESPACE "USERS" ;

CREATE TABLE "T_NULL_LINK_DEMO_DEST" (
    "TECH_KEY" VARCHAR2(256 BYTE) NOT NULL,
	"CODE" VARCHAR2(256 BYTE) NOT NULL,
	"BIZ_KEY" VARCHAR2(256 BYTE),
	CONSTRAINT "T_NULL_LINK_DEMO_DEST_PK" PRIMARY KEY ("TECH_KEY") USING INDEX ENABLE
) TABLESPACE "USERS" ;

INSERT INTO "T_NULL_LINK_DEMO_SRC"("ID", "VALUE", "DEST_BIZ_KEY") VALUES ('AAAAAAAA1', 'Value demo biz key rules 1', 'biz_key_dest_1');
INSERT INTO "T_NULL_LINK_DEMO_SRC"("ID", "VALUE", "DEST_BIZ_KEY") VALUES ('AAAAAAAA2', 'Value demo biz key rules 2', 'biz_key_dest_2');
INSERT INTO "T_NULL_LINK_DEMO_SRC"("ID", "VALUE", "DEST_BIZ_KEY") VALUES ('AAAAAAAA3', 'Value demo biz key rules 3', 'biz_key_dest_2');

INSERT INTO "T_NULL_LINK_DEMO_DEST"("TECH_KEY", "CODE", "BIZ_KEY") VALUES ('key_dest_1', 'Value dest_2', 'biz_key_dest_1');
INSERT INTO "T_NULL_LINK_DEMO_DEST"("TECH_KEY", "CODE", "BIZ_KEY") VALUES ('key_dest_2', 'Value dest_2', 'biz_key_dest_2');
INSERT INTO "T_NULL_LINK_DEMO_DEST"("TECH_KEY", "CODE", "BIZ_KEY") VALUES ('key_dest_3', 'Value dest_2', 'biz_key_dest_3');
INSERT INTO "T_NULL_LINK_DEMO_DEST"("TECH_KEY", "CODE", "BIZ_KEY") VALUES ('key_dest_4', 'Value dest_2', 'biz_key_dest_4');

COMMIT;

EXEC DBMS_STATS.gather_schema_stats('DEMO', cascade=>TRUE);