
CREATE TABLE "T_WITH_TEXT" (
                           "ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           "CODE_SERIE" VARCHAR2(128 BYTE) NOT NULL,
                           "CREATE_DATE" TIMESTAMP,
                           "FABRICANT" VARCHAR2(256 BYTE) NOT NULL,
                           "DESCRIPTION" VARCHAR2(1024 BYTE) NOT NULL,
                           "CONFIG_VALUE" CLOB,
                           "ACTIF" SMALLINT NOT NULL,
                           CONSTRAINT "T_WITH_TEXT_pkey" PRIMARY KEY ("ID")
) TABLESPACE "USERS" ;


INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0004_JSON', '02-01-2018 23:42:32', 'DUPON', 'Un modèle de test - 4', '{"listeChampsObjetTraite":"reprogrammee,0","listeChampsObjetConnexe":null,"listeChampsEDP":null}', 1);
INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0005_JSON', '02-01-2018 23:42:33', 'DUPON', 'Un modèle de test - 5', '{"listeChampsObjetTraite":"reprogrammee,0","listeChampsObjetConnexe":null,"listeChampsEDP":null}', 1);
INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0006_JSON', '02-01-2018 23:42:34', 'DUPON', 'Un modèle de test - 6', '{"processGenererDocument":null,"editerSurElementPopulation":false,"differe":false,"nombreExemplaire":1,"bacEntree":null,"modeDistribution":"1|com.hermes.arc.edition.type.EModeDistribution","modele":"31583643661|com.hermes.arc.edition.businessobject.ModeleDocumentPersonnalise","imprimante":null}', 1);
INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0007_TXT', '02-01-2018 23:42:34', 'DUPON', 'Un modèle de test - 7', 'pas un json, juste un texte\n avec des sauts de lignes 1', 1);
INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0008_TXT', '02-01-2018 23:42:34', 'DUPON', 'Un modèle de test - 8', 'pas un json, juste un texte\n avec des sauts de lignes 2', 0);
INSERT INTO "T_WITH_TEXT"("CODE_SERIE", "CREATE_DATE", "FABRICANT", "DESCRIPTION", "CONFIG_VALUE", "ACTIF") VALUES ('ABB0009_TXT', '02-01-2018 23:42:34', 'DUPON', 'Un modèle de test - 9', 'pas un json, juste un texte\n avec des sauts de lignes 3', 1);


EXEC DBMS_STATS.gather_schema_stats('DEMO', cascade=>TRUE);