-- Minimal required index spec
CREATE INDEX IDX_INDEXES_KEY ON INDEXES(KEY_VALUE);
CREATE INDEX IDX_INDEXES_ACTION ON INDEXES(ACTION);
CREATE INDEX IDX_DICTIONARY_TABLE_NAME ON DICTIONARY(TABLE_NAME);