-- Support more history change type
ALTER TABLE "APPLY_HISTORY" ADD "TYPE" VARCHAR2(10);

-- Upgrade existing values
UPDATE "APPLY_HISTORY" SET "TYPE" = 'ROLLBACK' WHERE "ROLLBACK" = 1;
UPDATE "APPLY_HISTORY" SET "TYPE" = 'IMPORT' WHERE "ROLLBACK" = 0;

-- Drop unused ROLLBACK status
ALTER TABLE "APPLY_HISTORY" DROP COLUMN "ROLLBACK";