CREATE TABLE "TRANSFORMERS" (
    "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6) NOT NULL ENABLE,
	"UPDATED_TIME" TIMESTAMP (6) NOT NULL ENABLE,
	"IMPORTED_TIME" TIMESTAMP (6),
	"PRIORITY" NUMBER(19,0) NOT NULL,
	"TYPE" VARCHAR2(511 CHAR),
	"PROJECT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONFIGURATION" CLOB,
	 PRIMARY KEY ("UUID") ENABLE,
	 CONSTRAINT "TRANSFORMER_PROJECT" FOREIGN KEY ("PROJECT_UUID") REFERENCES "PROJECTS" ("UUID") ENABLE
);
