DROP TABLE "TTABLEOTHER";
DROP TABLE "TMODELE";
DROP TABLE "TTYPEMATERIEL";
DROP TABLE "TCATEGORYMATERIEL";
DROP TABLE "TTABLEOTHERTEST2";
DROP TABLE "NOT_USED";

  CREATE TABLE "TCATEGORYMATERIEL" 
   (	"ID" NUMBER NOT NULL, 
		"NOM" VARCHAR2(256 BYTE) NOT NULL, 
		"DETAIL" VARCHAR2(256 BYTE) NOT NULL,
		CONSTRAINT "TCATEGORYMATERIEL_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
   ) TABLESPACE "USERS" ;

  
CREATE TABLE "TTYPEMATERIEL"
(
    "ID" NUMBER NOT NULL,
    "TYPE" VARCHAR2(256 BYTE) NOT NULL,
    "SERIE" VARCHAR2(256 BYTE),
    "CATID" NUMBER NOT NULL,
    CONSTRAINT "TTYPEMATERIEL_PK" PRIMARY KEY ("ID") USING INDEX ENABLE,
    CONSTRAINT "CAT_TYPE" FOREIGN KEY ("CATID") REFERENCES "TCATEGORYMATERIEL" ("ID") 
) TABLESPACE "USERS" ;


CREATE TABLE "TTABLEOTHER"
(
    "ID" NUMBER NOT NULL,
    "VALUE" VARCHAR2(256 BYTE) NOT NULL,
    "COUNT" NUMBER,
    "WHEN" TIMESTAMP,
    "TYPEID" NUMBER NOT NULL,
    CONSTRAINT "TTABLEOTHER_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "TYPE_OTHE" FOREIGN KEY ("TYPEID") REFERENCES "TTYPEMATERIEL" ("ID") 
) TABLESPACE "USERS" ;


CREATE TABLE "TTABLEOTHERTEST2"
(
    "ID" NUMBER NOT NULL,
    "VALUE1" VARCHAR2(256 BYTE) NOT NULL,
    "VALUE2" VARCHAR2(256 BYTE) NOT NULL,
    "VALUE3" VARCHAR2(256 BYTE) NOT NULL,
    "WEIGHT" FLOAT,
    "LAST_UPDATED" TIMESTAMP,
    CONSTRAINT "TTABLEOTHERTEST2_pkey" PRIMARY KEY ("ID")
) TABLESPACE "USERS" ;


CREATE TABLE "TMODELE"
(
    "ID" NUMBER NOT NULL,
    "CODE_SERIE" VARCHAR2(128 BYTE) NOT NULL,
    "CREATE_DATE" TIMESTAMP,
    "FABRICANT" VARCHAR2(256 BYTE) NOT NULL,
    "DESCRIPTION" VARCHAR2(1024 BYTE) NOT NULL,
    "TYPEID" NUMBER NOT NULL,
    "ACTIF" SMALLINT NOT NULL,
    CONSTRAINT "TMODELE_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "TYPE_MODE" FOREIGN KEY ("TYPEID") REFERENCES "TTYPEMATERIEL" ("ID") 
) TABLESPACE "USERS" ;


CREATE TABLE "NOT_USED"
(
    "ID" NUMBER NOT NULL,
    "VALUE" VARCHAR2(256 BYTE) NOT NULL,
    "WEIGHT" FLOAT,
    "LAST_UPDATED" TIMESTAMP,
    CONSTRAINT "NOT_USED_pkey" PRIMARY KEY ("ID")
) TABLESPACE "USERS" ;



-- Pour l'instant des données très simples.

INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (1, 'Something1', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (2, 'Something2', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (3, 'Something3', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (4, 'Something4', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (5, 'Something5', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (6, 'Something6', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (7, 'Something7', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (8, 'Something8', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (9, 'Something9', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (10, 'Something10', 'test', 'test2', 14.5, '02-01-2018 23:45:32');
INSERT INTO "TTABLEOTHERTEST2"("ID", "VALUE1", "VALUE2", "VALUE3", "WEIGHT", "LAST_UPDATED") VALUES (11, 'Something11', 'test', 'test2', 14.5, '02-01-2018 23:45:32');


