-- Warning : this script drop all MANAGER database (for restoration for example)

  DROP TABLE "TRANSFORMERS" ;
  DROP TABLE "APPLY_HISTORY" ;
  DROP TABLE "ATTACHMENTS" ;
  DROP TABLE "COMMIT_MERGE_SOURCES" ;
  DROP TABLE "INDEXES" ;
  DROP TABLE "LOBS" ;
  DROP TABLE "EXPORT_TRANSFORMERS";
  DROP TABLE "EXPORTS";
  DROP TABLE "COMMITS" ;
  DROP TABLE "LINK" ;
  DROP TABLE "MAPPINGS" ;
  DROP TABLE "USERS_PREFERED_PROJECTS" ;
  DROP TABLE "USERS" ;
  DROP TABLE "DICTIONARY" ;
  DROP TABLE "DOMAIN" ;
  DROP TABLE "VERSIONS" ;
  DROP TABLE "TRANSFORMERS";
  DROP TABLE "PROJECTS" ;
  DROP TABLE "FEATURES" ;

  DROP SEQUENCE "HIBERNATE_SEQUENCE"  ;

  DROP TABLE "flyway_schema_history";