--------------------------------------------------------
--  Fichier créé - mercredi-mars-11-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table APPLY_HISTORY
--------------------------------------------------------

  CREATE TABLE "APPLY_HISTORY"
   (	"ID" NUMBER(19,0),
	"ATTACHMENT_SOURCE_UUID" VARCHAR2(255 CHAR),
	"QUERY" CLOB,
	"ROLLBACK" NUMBER(1,0),
	"TIMESTAMP" NUMBER(19,0),
	"USER_LOGIN" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("QUERY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "ATTACHMENTS"
   (	"UUID" VARCHAR2(255 CHAR),
	"DATA" BLOB,
	"EXECUTE_TIME" TIMESTAMP (6),
	"IMPORTED_TIME" TIMESTAMP (6),
	"NAME" VARCHAR2(255 CHAR),
	"TYPE" NUMBER(10,0),
	"COMMIT_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table COMMIT_MERGE_SOURCES
--------------------------------------------------------

  CREATE TABLE "COMMIT_MERGE_SOURCES"
   (	"COMMIT_UUID" VARCHAR2(255 CHAR),
	"MERGE_SOURCES" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMITS
--------------------------------------------------------

  CREATE TABLE "COMMITS"
   (	"UUID" VARCHAR2(255 CHAR),
	"COMMENTS" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"HASHV" VARCHAR2(255 CHAR),
	"IMPORTED_TIME" TIMESTAMP (6),
	"ORIGINAL_USER_EMAIL" VARCHAR2(255 CHAR),
	"STATE" VARCHAR2(255 CHAR),
	"PROJECT_UUID" VARCHAR2(255 CHAR),
	"USER_LOGIN" VARCHAR2(255 CHAR),
	"VERSION_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DICTIONARY
--------------------------------------------------------

  CREATE TABLE "DICTIONARY"
   (	"UUID" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"EXT1KEY_NAME" VARCHAR2(255 CHAR),
	"EXT1KEY_TYPE" VARCHAR2(255 CHAR),
	"EXT2KEY_NAME" VARCHAR2(255 CHAR),
	"EXT2KEY_TYPE" VARCHAR2(255 CHAR),
	"EXT3KEY_NAME" VARCHAR2(255 CHAR),
	"EXT3KEY_TYPE" VARCHAR2(255 CHAR),
	"EXT4KEY_NAME" VARCHAR2(255 CHAR),
	"EXT4KEY_TYPE" VARCHAR2(255 CHAR),
	"IMPORTED_TIME" TIMESTAMP (6),
	"KEY_NAME" VARCHAR2(255 CHAR),
	"KEY_TYPE" VARCHAR2(255 CHAR),
	"PARAMETER_NAME" VARCHAR2(255 CHAR),
	"SELECT_CLAUSE" VARCHAR2(2048 CHAR),
	"TABLE_NAME" VARCHAR2(255 CHAR),
	"UPDATED_TIME" TIMESTAMP (6),
	"WHERE_CLAUSE" VARCHAR2(255 CHAR),
	"DOMAIN_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOMAIN
--------------------------------------------------------

  CREATE TABLE "DOMAIN"
   (	"UUID" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"IMPORTED_TIME" TIMESTAMP (6),
	"NAME" VARCHAR2(255 CHAR),
	"UPDATED_TIME" TIMESTAMP (6),
	"PROJECT_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FEATURES
--------------------------------------------------------

  CREATE TABLE "FEATURES"
   (	"FEATURE" VARCHAR2(255 CHAR),
	"ENABLED" NUMBER(1,0),
	"UPDATED_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INDEXES
--------------------------------------------------------

  CREATE TABLE "INDEXES"
   (	"ID" NUMBER(19,0),
	"ACTION" VARCHAR2(255 CHAR),
	"KEY_VALUE" VARCHAR2(255 CHAR),
	"PAYLOAD" CLOB,
	"TIMESTAMP" NUMBER(19,0),
	"COMMIT_UUID" VARCHAR2(255 CHAR),
	"DICTIONARY_ENTRY_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table LINK
--------------------------------------------------------

  CREATE TABLE "LINK"
   (	"UUID" VARCHAR2(255 CHAR),
	"COLUMN_FROM" VARCHAR2(255 CHAR),
	"COLUMN_TO" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"EXT1COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT1COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT2COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT2COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT3COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT3COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT4COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT4COLUMN_TO" VARCHAR2(255 CHAR),
	"IMPORTED_TIME" TIMESTAMP (6),
	"NAME" VARCHAR2(255 CHAR),
	"TABLE_TO" VARCHAR2(255 CHAR),
	"UPDATED_TIME" TIMESTAMP (6),
	"DICTIONARY_ENTRY_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOBS
--------------------------------------------------------

  CREATE TABLE "LOBS"
   (	"ID" NUMBER(19,0),
	"DATA" BLOB,
	"HASH" VARCHAR2(255 CHAR),
	"COMMIT_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table MAPPINGS
--------------------------------------------------------

  CREATE TABLE "MAPPINGS"
   (	"UUID" VARCHAR2(255 CHAR),
	"COLUMN_FROM" VARCHAR2(255 CHAR),
	"COLUMN_TO" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"EXT1COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT1COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT2COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT2COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT3COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT3COLUMN_TO" VARCHAR2(255 CHAR),
	"EXT4COLUMN_FROM" VARCHAR2(255 CHAR),
	"EXT4COLUMN_TO" VARCHAR2(255 CHAR),
	"IMPORTED_TIME" TIMESTAMP (6),
	"MAP_TABLE" VARCHAR2(255 CHAR),
	"MAP_TABLE_COLUMN_FROM" VARCHAR2(255 CHAR),
	"MAP_TABLE_COLUMN_TO" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT1COLUMN_FROM" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT1COLUMN_TO" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT2COLUMN_FROM" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT2COLUMN_TO" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT3COLUMN_FROM" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT3COLUMN_TO" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT4COLUMN_FROM" VARCHAR2(255 CHAR),
	"MAP_TABLE_EXT4COLUMN_TO" VARCHAR2(255 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"TABLE_TO" VARCHAR2(255 CHAR),
	"UPDATED_TIME" TIMESTAMP (6),
	"WHERE_CLAUSE" VARCHAR2(255 CHAR),
	"DICTIONARY_ENTRY_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECTS
--------------------------------------------------------

  CREATE TABLE "PROJECTS"
   (	"UUID" VARCHAR2(255 CHAR),
	"COLOR" NUMBER(10,0),
	"CREATED_TIME" TIMESTAMP (6),
	"IMPORTED_TIME" TIMESTAMP (6),
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS"
   (	"LOGIN" VARCHAR2(255 CHAR),
	"EMAIL" VARCHAR2(255 CHAR),
	"PASSWORD" VARCHAR2(255 CHAR),
	"TOKEN" VARCHAR2(255 CHAR),
	"SELECTED_PROJECT_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS_PREFERED_PROJECTS
--------------------------------------------------------

  CREATE TABLE "USERS_PREFERED_PROJECTS"
   (	"USER_LOGIN" VARCHAR2(255 CHAR),
	"PREFERED_PROJECTS_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VERSIONS
--------------------------------------------------------

  CREATE TABLE "VERSIONS"
   (	"UUID" VARCHAR2(255 CHAR),
	"CREATED_TIME" TIMESTAMP (6),
	"DICTIONARY_CONTENT" CLOB,
	"DOMAINS_CONTENT" CLOB,
	"IMPORTED_TIME" TIMESTAMP (6),
	"LINKS_CONTENT" CLOB,
	"MAPPINGS_CONTENT" CLOB,
	"MODEL_IDENTITY" VARCHAR2(255 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"UPDATED_TIME" TIMESTAMP (6),
	"PROJECT_UUID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("DICTIONARY_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DOMAINS_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("LINKS_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("MAPPINGS_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  Constraints for Table MAPPINGS
--------------------------------------------------------

  ALTER TABLE "MAPPINGS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("COLUMN_TO" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("MAP_TABLE" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("MAP_TABLE_COLUMN_FROM" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("MAP_TABLE_COLUMN_TO" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("TABLE_TO" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" MODIFY ("DICTIONARY_ENTRY_UUID" NOT NULL ENABLE);
  ALTER TABLE "MAPPINGS" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMITS
--------------------------------------------------------

  ALTER TABLE "COMMITS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "COMMITS" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "COMMITS" MODIFY ("PROJECT_UUID" NOT NULL ENABLE);
  ALTER TABLE "COMMITS" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "COMMITS" MODIFY ("VERSION_UUID" NOT NULL ENABLE);
  ALTER TABLE "COMMITS" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOMAIN
--------------------------------------------------------

  ALTER TABLE "DOMAIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DOMAIN" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "DOMAIN" MODIFY ("PROJECT_UUID" NOT NULL ENABLE);
  ALTER TABLE "DOMAIN" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DOMAIN" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "DOMAIN" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "ATTACHMENTS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENTS" MODIFY ("COMMIT_UUID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENTS" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DICTIONARY
--------------------------------------------------------

  ALTER TABLE "DICTIONARY" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("KEY_NAME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("KEY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("DOMAIN_UUID" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPLY_HISTORY
--------------------------------------------------------

  ALTER TABLE "APPLY_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APPLY_HISTORY" MODIFY ("ROLLBACK" NOT NULL ENABLE);
  ALTER TABLE "APPLY_HISTORY" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "APPLY_HISTORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOBS
--------------------------------------------------------

  ALTER TABLE "LOBS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LOBS" MODIFY ("COMMIT_UUID" NOT NULL ENABLE);
  ALTER TABLE "LOBS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VERSIONS
--------------------------------------------------------

  ALTER TABLE "VERSIONS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "VERSIONS" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "VERSIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "VERSIONS" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "VERSIONS" MODIFY ("PROJECT_UUID" NOT NULL ENABLE);
  ALTER TABLE "VERSIONS" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LINK
--------------------------------------------------------

  ALTER TABLE "LINK" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "LINK" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "LINK" MODIFY ("TABLE_TO" NOT NULL ENABLE);
  ALTER TABLE "LINK" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "LINK" MODIFY ("DICTIONARY_ENTRY_UUID" NOT NULL ENABLE);
  ALTER TABLE "LINK" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "USERS" ADD PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS_PREFERED_PROJECTS
--------------------------------------------------------

  ALTER TABLE "USERS_PREFERED_PROJECTS" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "USERS_PREFERED_PROJECTS" MODIFY ("PREFERED_PROJECTS_UUID" NOT NULL ENABLE);
  ALTER TABLE "USERS_PREFERED_PROJECTS" ADD PRIMARY KEY ("USER_LOGIN", "PREFERED_PROJECTS_UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECTS
--------------------------------------------------------

  ALTER TABLE "PROJECTS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "PROJECTS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "PROJECTS" MODIFY ("CREATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "PROJECTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECTS" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FEATURES
--------------------------------------------------------

  ALTER TABLE "FEATURES" MODIFY ("FEATURE" NOT NULL ENABLE);
  ALTER TABLE "FEATURES" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "FEATURES" MODIFY ("UPDATED_TIME" NOT NULL ENABLE);
  ALTER TABLE "FEATURES" ADD PRIMARY KEY ("FEATURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INDEXES
--------------------------------------------------------

  ALTER TABLE "INDEXES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INDEXES" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "INDEXES" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "INDEXES" MODIFY ("DICTIONARY_ENTRY_UUID" NOT NULL ENABLE);
  ALTER TABLE "INDEXES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMIT_MERGE_SOURCES
--------------------------------------------------------

  ALTER TABLE "COMMIT_MERGE_SOURCES" MODIFY ("COMMIT_UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPLY_HISTORY
--------------------------------------------------------

  ALTER TABLE "APPLY_HISTORY" ADD CONSTRAINT "FK36W4YOI8UYIAQF46M8WVC2V1F" FOREIGN KEY ("USER_LOGIN")
	  REFERENCES "USERS" ("LOGIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "ATTACHMENTS" ADD CONSTRAINT "FK4R1CGHC9Y4QQHPHB24H73MI90" FOREIGN KEY ("COMMIT_UUID")
	  REFERENCES "COMMITS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMIT_MERGE_SOURCES
--------------------------------------------------------

  ALTER TABLE "COMMIT_MERGE_SOURCES" ADD CONSTRAINT "FK5FMT2KOSDD75IW54VFSONAE04" FOREIGN KEY ("COMMIT_UUID")
	  REFERENCES "COMMITS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMITS
--------------------------------------------------------

  ALTER TABLE "COMMITS" ADD CONSTRAINT "FKDFF92T1Q0JUM0JHDR3UX3VS5N" FOREIGN KEY ("PROJECT_UUID")
	  REFERENCES "PROJECTS" ("UUID") ENABLE;
  ALTER TABLE "COMMITS" ADD CONSTRAINT "FKCRXSL08VPIDG1JLBLG91733QM" FOREIGN KEY ("USER_LOGIN")
	  REFERENCES "USERS" ("LOGIN") ENABLE;
  ALTER TABLE "COMMITS" ADD CONSTRAINT "FKRG02NQ4CF8NRBMBXVOIV0HV5A" FOREIGN KEY ("VERSION_UUID")
	  REFERENCES "VERSIONS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DICTIONARY
--------------------------------------------------------

  ALTER TABLE "DICTIONARY" ADD CONSTRAINT "FKTDB0NMJMM7HJ1G68J7I4144L0" FOREIGN KEY ("DOMAIN_UUID")
	  REFERENCES "DOMAIN" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOMAIN
--------------------------------------------------------

  ALTER TABLE "DOMAIN" ADD CONSTRAINT "FK5MPCIFF1LKE968GYSY3CYQG6O" FOREIGN KEY ("PROJECT_UUID")
	  REFERENCES "PROJECTS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INDEXES
--------------------------------------------------------

  ALTER TABLE "INDEXES" ADD CONSTRAINT "FK4T7JKJBU0T0U8MOJ7KGI7UK9X" FOREIGN KEY ("COMMIT_UUID")
	  REFERENCES "COMMITS" ("UUID") ENABLE;
  ALTER TABLE "INDEXES" ADD CONSTRAINT "FKAHYRBR6F6MYK6PSUEJWM4UVMK" FOREIGN KEY ("DICTIONARY_ENTRY_UUID")
	  REFERENCES "DICTIONARY" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINK
--------------------------------------------------------

  ALTER TABLE "LINK" ADD CONSTRAINT "FK7YKAX677KKW47JDLVNGI0O1AS" FOREIGN KEY ("DICTIONARY_ENTRY_UUID")
	  REFERENCES "DICTIONARY" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOBS
--------------------------------------------------------

  ALTER TABLE "LOBS" ADD CONSTRAINT "FKAVWAHYLTTCGLUU36W5HFRD8YT" FOREIGN KEY ("COMMIT_UUID")
	  REFERENCES "COMMITS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAPPINGS
--------------------------------------------------------

  ALTER TABLE "MAPPINGS" ADD CONSTRAINT "FKGCA6WB8B01675SB5VT9YUS7QL" FOREIGN KEY ("DICTIONARY_ENTRY_UUID")
	  REFERENCES "DICTIONARY" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "FKNBDXGWTQQ32QA6O3P4H9FDF9X" FOREIGN KEY ("SELECTED_PROJECT_UUID")
	  REFERENCES "PROJECTS" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_PREFERED_PROJECTS
--------------------------------------------------------

  ALTER TABLE "USERS_PREFERED_PROJECTS" ADD CONSTRAINT "FKPY4YLS0LQNVKFGDU1BEL6RI2X" FOREIGN KEY ("PREFERED_PROJECTS_UUID")
	  REFERENCES "PROJECTS" ("UUID") ENABLE;
  ALTER TABLE "USERS_PREFERED_PROJECTS" ADD CONSTRAINT "FKPOA1WG9CJKNJKWTWEDI0HRYPY" FOREIGN KEY ("USER_LOGIN")
	  REFERENCES "USERS" ("LOGIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VERSIONS
--------------------------------------------------------

  ALTER TABLE "VERSIONS" ADD CONSTRAINT "FK8XVR1CPK7YXQA1WYOYCA1VVX3" FOREIGN KEY ("PROJECT_UUID")
	  REFERENCES "PROJECTS" ("UUID") ENABLE;

COMMIT;