-- Init tables for recette copy

DROP TABLE "T_RECETTE_COMPOSITE";

-- CASE : Single Table with composite key

CREATE TABLE "T_RECETTE_COMPOSITE" (
	"ID_ONE" NUMBER(19,0) NOT NULL,
	"ID_TWO" NUMBER(19,0) NOT NULL,
	"VALUE" VARCHAR2(256 BYTE) NOT NULL,
	"DETAILS" VARCHAR2(256 BYTE) NOT NULL,
	CONSTRAINT "T_RECETTE_COMPOSITE_PK" PRIMARY KEY ("ID_ONE", "ID_TWO") USING INDEX ENABLE
) TABLESPACE "USERS" ;


insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (1, 1, 'VALUE 11', 'DETAILS 11');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (1, 2, 'VALUE 12', 'DETAILS 12');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (1, 3, 'VALUE 13', 'DETAILS 13');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (1, 4, 'VALUE 14', 'DETAILS 14');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (1, 5, 'VALUE 15', 'DETAILS 15');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (2, 1, 'VALUE 21', 'DETAILS 21');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (2, 2, 'VALUE 22', 'DETAILS 22');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (2, 3, 'VALUE 23', 'DETAILS 23');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (2, 4, 'VALUE 24', 'DETAILS 24');
insert into "T_RECETTE_COMPOSITE" ("ID_ONE", "ID_TWO", "VALUE", "DETAILS") values (2, 5, 'VALUE 25', 'DETAILS 25');